name: unet_crypto
description: >
  Standalone, auditable crypto modules for UNET.
  Registration, authentication, account recovery, DM end-to-end encryption.
publish_to: 'none'

environment:
  sdk: ^3.10.7

dependencies:
  sodium_libs: 3.3.0
  convert: ^3.1.2
  crypto: ^3.0.6
  argon2: ^1.0.1
  meta: ^1.17.0

dev_dependencies:
  test: ^1.26.3
  sodium: ^3.4.6
